apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-git-link
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.devlake: ""
    notifications.argoproj.io/subscribe.on-app-status-progressing.devlake: ""
    notifications.argoproj.io/subscribe.on-app-status-healthy.devlake: ""
spec:
  project: default
  source:
    repoURL: https://github.com/Pratiyush05Pushkar/Hello-world.git
    targetRevision: HEAD
    path: yamls
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true