apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devlake-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Pratiyush05Pushkar/Hello-world.git
    targetRevision: HEAD
    path: devlake-in-single-file
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true